
Schema.voices.Add("Combine", "0", "Zero.", "npc/metropolice/vo/zero.wav")
Schema.voices.Add("Combine", "1", "One.", "npc/metropolice/vo/one.wav")
Schema.voices.Add("Combine", "10", "Ten.", "npc/metropolice/vo/ten.wav")
Schema.voices.Add("Combine", "10-0 HUNTING", "10-0, 10-0, viscerator is hunting!", "npc/metropolice/vo/tenzerovisceratorishunting.wav")
Schema.voices.Add("Combine", "100", "One-hundred.", "npc/metropolice/vo/onehundred.wav")
Schema.voices.Add("Combine", "10-103 TAG", "Possible 10-103, my location, alert TAG units.", "npc/metropolice/vo/possible10-103alerttagunits.wav")
Schema.voices.Add("Combine", "10-107", "I have a 10-107 here, send AirWatch for tag.", "npc/metropolice/vo/gota10-107sendairwatch.wav")
Schema.voices.Add("Combine", "10-108", "We have a 10-108!", "npc/metropolice/vo/wehavea10-108.wav")
Schema.voices.Add("Combine", "10-14", "Holding on 10-14 duty, eh, code four.", "npc/metropolice/vo/holdingon10-14duty.wav")
Schema.voices.Add("Combine", "10-15", "Prepare for 10-15.", "npc/metropolice/vo/preparefor1015.wav")
Schema.voices.Add("Combine", "10-2", "10-2.", "npc/metropolice/vo/ten2.wav")
Schema.voices.Add("Combine", "10-25", "Any unit, report in with 10-25 as suspect.", "npc/metropolice/vo/unitreportinwith10-25suspect.wav")
Schema.voices.Add("Combine", "10-30", "I have a 10-30, my 10-20, responding, code two.", "npc/metropolice/vo/Ihave10-30my10-20responding.wav")
Schema.voices.Add("Combine", "10-4", "10-4.", "npc/metropolice/vo/ten4.wav")
Schema.voices.Add("Combine", "10-65", "Unit is 10-65.", "npc/metropolice/vo/unitis10-65.wav")
Schema.voices.Add("Combine", "10-78", "Dispatch, I need 10-78, officer in trouble!", "npc/metropolice/vo/dispatchIneed10-78.wav")
Schema.voices.Add("Combine", "10-8 standing by", "10-8, standing by.", "npc/metropolice/vo/ten8standingby.wav")
Schema.voices.Add("Combine", "10-8", "Unit is on-duty, 10-8.", "npc/metropolice/vo/unitisonduty10-8.wav")
Schema.voices.Add("Combine", "10-91D", "10-91d count is...", "npc/metropolice/vo/ten91dcountis.wav")
Schema.voices.Add("Combine", "10-97 GOA", "10-97, that suspect is GOA.", "npc/metropolice/vo/ten97suspectisgoa.wav")
Schema.voices.Add("Combine", "10-97", "10-97.", "npc/metropolice/vo/ten97.wav")
Schema.voices.Add("Combine", "10-99", "Officer down, I am 10-99, I repeat, I am 10-99!", "npc/metropolice/vo/officerdownIam10-99.wav")
Schema.voices.Add("Combine", "11-44", "Get that 11-44 inbound, we're cleaning up now.", "npc/metropolice/vo/get11-44inboundcleaningup.wav")
Schema.voices.Add("Combine", "11-6", "Suspect 11-6, my 10-20 is...", "npc/metropolice/vo/suspect11-6my1020is.wav")
Schema.voices.Add("Combine", "11-99", "11-99, officer needs assistance!", "npc/metropolice/vo/11-99officerneedsassistance.wav")
Schema.voices.Add("Combine", "2", "Two.", "npc/metropolice/vo/two.wav")
Schema.voices.Add("Combine", "20", "Twenty.", "npc/metropolice/vo/twenty.wav")
Schema.voices.Add("Combine", "200", "Two-hundred.", "npc/metropolice/vo/twohundred.wav")
Schema.voices.Add("Combine", "3", "Three.", "npc/metropolice/vo/three.wav")
Schema.voices.Add("Combine", "30", "Thirty.", "npc/metropolice/vo/thirty.wav")
Schema.voices.Add("Combine", "300", "Three-hundred.", "npc/metropolice/vo/threehundred.wav")
Schema.voices.Add("Combine", "34S AT", "All units, BOL, we have 34-S at...", "npc/metropolice/vo/allunitsbol34sat.wav")
Schema.voices.Add("Combine", "4", "Four.", "npc/metropolice/vo/four.wav")
Schema.voices.Add("Combine", "40", "Fourty.", "npc/metropolice/vo/fourty.wav")
Schema.voices.Add("Combine", "404", "404 zone.", "npc/metropolice/vo/404zone.wav")
Schema.voices.Add("Combine", "408", "I've got a 408 here at location.", "npc/metropolice/vo/Ivegot408hereatlocation.wav")
Schema.voices.Add("Combine", "415B", "Is 415b.", "npc/metropolice/vo/is415b.wav")
Schema.voices.Add("Combine", "5", "Five.", "npc/metropolice/vo/five.wav")
Schema.voices.Add("Combine", "50", "Fifty.", "npc/metropolice/vo/fifty.wav")
Schema.voices.Add("Combine", "505", "Dispatch, we need AirWatch, subject is 505!", "npc/metropolice/vo/airwatchsubjectis505.wav")
Schema.voices.Add("Combine", "6", "Six.", "npc/metropolice/vo/six.wav")
Schema.voices.Add("Combine", "60", "Sixty.", "npc/metropolice/vo/sixty.wav")
Schema.voices.Add("Combine", "603", "603, unlawful entry.", "npc/metropolice/vo/unlawfulentry603.wav")
Schema.voices.Add("Combine", "63", "63, criminal trespass.", "npc/metropolice/vo/criminaltrespass63.wav")
Schema.voices.Add("Combine", "7", "Seven.", "npc/metropolice/vo/seven.wav")
Schema.voices.Add("Combine", "70", "Seventy.", "npc/metropolice/vo/seventy.wav")
Schema.voices.Add("Combine", "8", "Eight.", "npc/metropolice/vo/eight.wav")
Schema.voices.Add("Combine", "80", "Eighty.", "npc/metropolice/vo/eighty.wav")
Schema.voices.Add("Combine", "9", "Nine.", "npc/metropolice/vo/nine.wav")
Schema.voices.Add("Combine", "90", "Ninety.", "npc/metropolice/vo/ninety.wav")
Schema.voices.Add("Combine", "THAT'S A GRENADE", "That's a grenade!", "npc/metropolice/vo/thatsagrenade.wav")
Schema.voices.Add("Combine", "ACQUIRING", "Acquiring on visual!", "npc/metropolice/vo/acquiringonvisual.wav")
Schema.voices.Add("Combine", "ADMINISTER", "Administer.", "npc/metropolice/vo/administer.wav")
Schema.voices.Add("Combine", "CONFIRMED ADW", "Confirmed as ADW on that suspect, 10-0.", "npc/metropolice/vo/confirmadw.wav")
Schema.voices.Add("Combine", "AFFIRMATIVE", "Affirmative.", "npc/metropolice/vo/affirmative.wav")
Schema.voices.Add("Combine", "ALL UNITS MOVE", "All units, move in!", "npc/metropolice/vo/allunitsmovein.wav")
Schema.voices.Add("Combine", "AMPUTATE", "Amputate.", "npc/metropolice/vo/amputate.wav")
Schema.voices.Add("Combine", "ANTICITIZEN", "Anti-citizen.", "npc/metropolice/vo/anticitizen.wav")
Schema.voices.Add("Combine", "ANTISEPTIC", "Antiseptic.", "npc/combine_soldier/vo/antiseptic.wav")
Schema.voices.Add("Combine", "APEX", "Apex.", "npc/combine_soldier/vo/apex.wav")
Schema.voices.Add("Combine", "APPLY", "Apply.", "npc/metropolice/vo/apply.wav")
Schema.voices.Add("Combine", "ARREST POSITIONS", "All units, move to arrest positions!", "npc/metropolice/vo/movetoarrestpositions.wav")
Schema.voices.Add("Combine", "AT CHECKPOINT", "At checkpoint.", "npc/metropolice/vo/atcheckpoint.wav")
Schema.voices.Add("Combine", "AT LOCATION REPORT", "Protection-teams at location, report in.", "npc/metropolice/vo/ptatlocationreport.wav")
Schema.voices.Add("Combine", "BACK ME UP", "Back me up, I'm out!", "npc/metropolice/vo/backmeupImout.wav")
Schema.voices.Add("Combine", "BACKUP", "Backup!", "npc/metropolice/vo/backup.wav")
Schema.voices.Add("Combine", "BLADE", "Blade.", "npc/combine_soldier/vo/blade.wav")
Schema.voices.Add("Combine", "BLEEDING", "Suspect is bleeding from multiple wounds!", "npc/metropolice/vo/suspectisbleeding.wav")
Schema.voices.Add("Combine", "BLIP", "Catch that blip on the stabilization readout?", "npc/metropolice/vo/catchthatbliponstabilization.wav")
Schema.voices.Add("Combine", "BLOCK HOLDING", "Block is holding, cohesive.", "npc/metropolice/vo/blockisholdingcohesive.wav")
Schema.voices.Add("Combine", "BLOCK", "Block!", "npc/metropolice/vo/block.wav")
Schema.voices.Add("Combine", "BOL 243", "CP, we need AirWatch to BOL for that 243.", "npc/metropolice/vo/cpbolforthat243.wav")
Schema.voices.Add("Combine", "BOOMER", "Boomer.", "npc/combine_soldier/vo/boomer.wav")
Schema.voices.Add("Combine", "BREAK COVER", "Break his cover!", "npc/metropolice/vo/breakhiscover.wav")
Schema.voices.Add("Combine", "CAN1", "Pick up that can.", "npc/metropolice/vo/pickupthecan1.wav")
Schema.voices.Add("Combine", "CAN2", "Pick up the can!", "npc/metropolice/vo/pickupthecan2.wav")
Schema.voices.Add("Combine", "CAN3", "I said, pick up the can!", "npc/metropolice/vo/pickupthecan3.wav")
Schema.voices.Add("Combine", "CAN4", "Now, put it in the trash-can.", "npc/metropolice/vo/putitinthetrash1.wav")
Schema.voices.Add("Combine", "CAN5", "I said, put it in the trash-can!", "npc/metropolice/vo/putitinthetrash2.wav")
Schema.voices.Add("Combine", "CAN6", "You knocked it over, pick it up!", "npc/metropolice/vo/youknockeditover.wav")
Schema.voices.Add("Combine", "CANAL", "Canal.", "npc/metropolice/vo/canal.wav")
Schema.voices.Add("Combine", "CANALBLOCK", "Canalblock!", "npc/metropolice/vo/canalblock.wav")
Schema.voices.Add("Combine", "CAUTERIZE", "Cauterize.", "npc/metropolice/vo/cauterize.wav")
Schema.voices.Add("Combine", "CHECK MISCOUNT", "Check for miscount.", "npc/metropolice/vo/checkformiscount.wav")
Schema.voices.Add("Combine", "CHECKPOINTS", "Proceed to designated checkpoints.", "npc/metropolice/vo/proceedtocheckpoints.wav")
Schema.voices.Add("Combine", "CITIZEN SUMMONED", "Reporting citizen summoned into voluntary conscription for channel open service detail T94-332.", "npc/metropolice/vo/citizensummoned.wav")
Schema.voices.Add("Combine", "CITIZEN", "Citizen.", "npc/metropolice/vo/citizen.wav")
Schema.voices.Add("Combine", "CLASSIFY DB", "Classify subject name as 'DB'; this block ready for clean-out.", "npc/metropolice/vo/classifyasdbthisblockready.wav")
Schema.voices.Add("Combine", "CLEANED", "Cleaned.", "npc/combine_soldier/vo/cleaned.wav")
Schema.voices.Add("Combine", "CLEAR CODE 100", "Clear and code one-hundred.", "npc/metropolice/vo/clearandcode100.wav")
Schema.voices.Add("Combine", "CLOSE ON SUSPECT", "All units, close on suspect!", "npc/metropolice/vo/allunitscloseonsuspect.wav")
Schema.voices.Add("Combine", "CLOSING", "Closing!", {"npc/combine_soldier/vo/closing.wav", "npc/combine_soldier/vo/closing2.wav"})
Schema.voices.Add("Combine", "CODE 100", "Code one-hundred.", "npc/metropolice/vo/code100.wav")
Schema.voices.Add("Combine", "CODE 2", "All units, code two!", "npc/metropolice/vo/allunitscode2.wav")
Schema.voices.Add("Combine", "CODE 3", "Officer down, request all units, code three to my 10-20!", "npc/metropolice/vo/officerdowncode3tomy10-20.wav")
Schema.voices.Add("Combine", "CODE 7", "Code seven.", "npc/metropolice/vo/code7.wav")
Schema.voices.Add("Combine", "CONDEMNED", "Condemned zone!", "npc/metropolice/vo/condemnedzone.wav")
Schema.voices.Add("Combine", "CONTACT 243", "Contact with 243 suspect, my 10-20 is...", "npc/metropolice/vo/contactwith243suspect.wav")
Schema.voices.Add("Combine", "CONTACT PRIORITY", "I have contact with a priority two!", "npc/metropolice/vo/contactwithpriority2.wav")
Schema.voices.Add("Combine", "CONTACT", "Contact!", "npc/combine_soldier/vo/contact.wav")
Schema.voices.Add("Combine", "CONTAINED", "Contained.", "npc/combine_soldier/vo/contained.wav")
Schema.voices.Add("Combine", "CONTROL 100", "Control is one-hundred percent this location, no sign of that 647-E.", "npc/metropolice/vo/control100percent.wav")
Schema.voices.Add("Combine", "CONTROLSECTION", "Control-section!", "npc/metropolice/vo/controlsection.wav")
Schema.voices.Add("Combine", "CONVERGING", "Converging.", "npc/metropolice/vo/converging.wav")
Schema.voices.Add("Combine", "COPY THAT", "Copy that.", "npc/combine_soldier/vo/copythat.wav")
Schema.voices.Add("Combine", "COPY", "Copy.", "npc/metropolice/vo/copy.wav")
Schema.voices.Add("Combine", "COVER", "Cover!", "npc/combine_soldier/vo/coverhurt.wav")
Schema.voices.Add("Combine", "CP COMPROMISED", "CP is compromised, re-establish!", "npc/metropolice/vo/cpiscompromised.wav")
Schema.voices.Add("Combine", "CP ESTABLISH", "CP, we need to establish our perimeter at...", "npc/metropolice/vo/cpweneedtoestablishaperimeterat.wav")
Schema.voices.Add("Combine", "CP OVERRUN", "CP is overrun, we have no containment!", "npc/metropolice/vo/cpisoverrunwehavenocontainment.wav")
Schema.voices.Add("Combine", "DAGGER", "Dagger.", "npc/combine_soldier/vo/dagger.wav")
Schema.voices.Add("Combine", "DASH", "Dash.", "npc/combine_soldier/vo/dash.wav")
Schema.voices.Add("Combine", "DB COUNT", "DB count is...", "npc/metropolice/vo/dbcountis.wav")
Schema.voices.Add("Combine", "DEFENDER", "Defender!", "npc/metropolice/vo/defender.wav")
Schema.voices.Add("Combine", "DESERVICED AREA", "Deserviced area.", "npc/metropolice/vo/deservicedarea.wav")
Schema.voices.Add("Combine", "DESIGNATE SUSPECT", "Designate suspect as...", "npc/metropolice/vo/designatesuspectas.wav")
Schema.voices.Add("Combine", "DESTROY COVER", "Destroy that cover!", "npc/metropolice/vo/destroythatcover.wav")
Schema.voices.Add("Combine", "DISLOCATE INTERPOSE", "Fire to dislocate that interpose!", "npc/metropolice/vo/firetodislocateinterpose.wav")
Schema.voices.Add("Combine", "DISMOUNTING HARDPOINT", "Dismounting hardpoint.", "npc/metropolice/vo/dismountinghardpoint.wav")
Schema.voices.Add("Combine", "DISP APB", "Disp updating APB likeness.", "npc/metropolice/vo/dispupdatingapb.wav")
Schema.voices.Add("Combine", "DISTRIBUTION BLOCK", "Distribution block.", "npc/metropolice/vo/distributionblock.wav")
Schema.voices.Add("Combine", "DOCUMENT", "Document.", "npc/metropolice/vo/document.wav")
Schema.voices.Add("Combine", "DONT MOVE", "Don't move!", "npc/metropolice/vo/dontmove.wav")
Schema.voices.Add("Combine", "ECHO", "Echo.", "npc/combine_soldier/vo/echo.wav")
Schema.voices.Add("Combine", "ENGAGING", "Engaging!", "npc/combine_soldier/vo/engaging.wav")
Schema.voices.Add("Combine", "ESTABLISH NEW CP", "Fall down, establish a new CP!", "npc/metropolice/vo/establishnewcp.wav")
Schema.voices.Add("Combine", "EXPOSE TARGET", "Firing to expose target!", "npc/metropolice/vo/firingtoexposetarget.wav")
Schema.voices.Add("Combine", "EXTERNAL", "External jurisdiction.", "npc/metropolice/vo/externaljurisdiction.wav")
Schema.voices.Add("Combine", "FINAL VERDICT", "Final verdict administered.", "npc/metropolice/vo/finalverdictadministered.wav")
Schema.voices.Add("Combine", "FINAL WARNING", "Final warning!", "npc/metropolice/vo/finalwarning.wav")
Schema.voices.Add("Combine", "FIRST WARNING", "First warning, move away!", "npc/metropolice/vo/firstwarningmove.wav")
Schema.voices.Add("Combine", "FIST", "Fist.", "npc/combine_soldier/vo/fist.wav")
Schema.voices.Add("Combine", "FLASH", "Flash.", "npc/combine_soldier/vo/flash.wav")
Schema.voices.Add("Combine", "FLATLINE", "Flatline.", "npc/combine_soldier/vo/flatline.wav")
Schema.voices.Add("Combine", "FLUSH", "Flush.", "npc/combine_soldier/vo/flush.wav")
Schema.voices.Add("Combine", "FREE NECROTICS", "I have free necrotics!", "npc/metropolice/vo/freenecrotics.wav")
Schema.voices.Add("Combine", "GET DOWN", "Get down!", "npc/metropolice/vo/getdown.wav")
Schema.voices.Add("Combine", "GET OUT", "Get out of here!", "npc/metropolice/vo/getoutofhere.wav")
Schema.voices.Add("Combine", "GETTING 647E", "Still getting that 647-E from local surveillance.", "npc/metropolice/vo/stillgetting647e.wav")
Schema.voices.Add("Combine", "GHOST", "Ghost.", "npc/combine_soldier/vo/ghost.wav")
Schema.voices.Add("Combine", "GO AGAIN", "PT, go again.", "npc/metropolice/vo/ptgoagain.wav")
Schema.voices.Add("Combine", "GO SHARP", "Go sharp!", "npc/combine_soldier/vo/gosharp.wav")
Schema.voices.Add("Combine", "GOING IN", "Cover me, I'm going in!", "npc/metropolice/vo/covermegoingin.wav")
Schema.voices.Add("Combine", "GOT A DB", "Uh, we got a DB here, cancel that 11-42.", "npc/metropolice/vo/wegotadbherecancel10-102.wav")
Schema.voices.Add("Combine", "GOT HIM AGAIN", "Got him again, suspect is 10-20 at...", "npc/metropolice/vo/gothimagainsuspect10-20at.wav")
Schema.voices.Add("Combine", "GOT ONE ACCOMPLICE", "I got one accomplice here!", "npc/metropolice/vo/gotoneaccomplicehere.wav")
Schema.voices.Add("Combine", "GOT SUSPECT ONE", "I got suspect one here!", "npc/metropolice/vo/gotsuspect1here.wav")
Schema.voices.Add("Combine", "GRENADE", "Grenade!", "npc/metropolice/vo/grenade.wav")
Schema.voices.Add("Combine", "GRID", "Grid.", "npc/combine_soldier/vo/grid.wav")
Schema.voices.Add("Combine", "HAHA", "Haha.", "npc/metropolice/vo/chuckle.wav")
Schema.voices.Add("Combine", "HAMMER", "Hammer.", "npc/combine_soldier/vo/hammer.wav")
Schema.voices.Add("Combine", "HARDPOINT PROSECUTE", "Is at hardpoint, ready to prosecute!", "npc/metropolice/vo/isathardpointreadytoprosecute.wav")
Schema.voices.Add("Combine", "HARDPOINT SCANNING", "Hardpoint scanning.", "npc/metropolice/vo/hardpointscanning.wav")
Schema.voices.Add("Combine", "HELIX", "Helix.", "npc/combine_soldier/vo/helix.wav")
Schema.voices.Add("Combine", "HELP", "Help!", "npc/metropolice/vo/help.wav")
Schema.voices.Add("Combine", "HERO", "Hero!", "npc/metropolice/vo/hero.wav")
Schema.voices.Add("Combine", "HES 148", "He's gone 148!", "npc/metropolice/vo/hesgone148.wav")
Schema.voices.Add("Combine", "HIGH PRIORITY", "High-priority region.", "npc/metropolice/vo/highpriorityregion.wav")
Schema.voices.Add("Combine", "HOLD IT", "Hold it right there!", "npc/metropolice/vo/holditrightthere.wav")
Schema.voices.Add("Combine", "HOLD POSITION", "Protection-team, hold this position.", "npc/metropolice/vo/holdthisposition.wav")
Schema.voices.Add("Combine", "HOLD", "Hold it!", "npc/metropolice/vo/holdit.wav")
Schema.voices.Add("Combine", "HUNTER", "Hunter.", "npc/combine_soldier/vo/hunter.wav")
Schema.voices.Add("Combine", "HURRICANE", "Hurricane.", "npc/combine_soldier/vo/hurricane.wav")
Schema.voices.Add("Combine", "I SAID MOVE", "I said move along.", "npc/metropolice/vo/Isaidmovealong.wav")
Schema.voices.Add("Combine", "ICE", "Ice.", "npc/combine_soldier/vo/ice.wav")
Schema.voices.Add("Combine", "IN POSITION", "In position.", "npc/metropolice/vo/inposition.wav")
Schema.voices.Add("Combine", "INBOUND", "Inbound.", "npc/combine_soldier/vo/inbound.wav")
Schema.voices.Add("Combine", "INFECTED", "Infected.", "npc/combine_soldier/vo/infected.wav")
Schema.voices.Add("Combine", "INFECTION", "Infection!", "npc/metropolice/vo/infection.wav")
Schema.voices.Add("Combine", "INFESTED", "Infested zone.", "npc/metropolice/vo/infestedzone.wav")
Schema.voices.Add("Combine", "INJECT", "Inject!", "npc/metropolice/vo/inject.wav")
Schema.voices.Add("Combine", "INOCULATE", "Inoculate.", "npc/metropolice/vo/innoculate.wav")
Schema.voices.Add("Combine", "INTERCEDE", "Intercede!", "npc/metropolice/vo/intercede.wav")
Schema.voices.Add("Combine", "INTERLOCK", "Interlock!", "npc/metropolice/vo/interlock.wav")
Schema.voices.Add("Combine", "INVESTIGATE", "Investigate.", "npc/metropolice/vo/investigate.wav")
Schema.voices.Add("Combine", "INVESTIGATING", "Investigating 10-103.", "npc/metropolice/vo/investigating10-103.wav")
Schema.voices.Add("Combine", "ION", "Ion.", "npc/combine_soldier/vo/ion.wav")
Schema.voices.Add("Combine", "IS 10-108", "Is 10-108!", "npc/metropolice/vo/is10-108.wav")
Schema.voices.Add("Combine", "IS 10-8", "Unit is 10-8, standing by.", "npc/metropolice/vo/unitis10-8standingby.wav")
Schema.voices.Add("Combine", "IS CLOSING", "Is closing on suspect!", "npc/metropolice/vo/isclosingonsuspect.wav")
Schema.voices.Add("Combine", "IS DOWN", "Is down!", "npc/metropolice/vo/isdown.wav")
Schema.voices.Add("Combine", "IS INBOUND", "Unit is inbound.", "npc/combine_soldier/vo/unitisinbound.wav")
Schema.voices.Add("Combine", "IS MOVING IN", "Unit is moving in.", "npc/combine_soldier/vo/unitismovingin.wav")
Schema.voices.Add("Combine", "IS MOVING", "Is moving in!", "npc/metropolice/vo/ismovingin.wav")
Schema.voices.Add("Combine", "IS PASSIVE", "Is passive.", "npc/metropolice/vo/ispassive.wav")
Schema.voices.Add("Combine", "IS READY TO GO", "Is ready to go!", "npc/metropolice/vo/isreadytogo.wav")
Schema.voices.Add("Combine", "ISOLATE", "Isolate!", "npc/metropolice/vo/isolate.wav")
Schema.voices.Add("Combine", "JET", "Jet.", "npc/combine_soldier/vo/jet.wav")
Schema.voices.Add("Combine", "JUDGE", "Judge.", "npc/combine_soldier/vo/judge.wav")
Schema.voices.Add("Combine", "JUDGMENT", "Suspect, prepare to receive civil judgment!", "npc/metropolice/vo/prepareforjudgement.wav")
Schema.voices.Add("Combine", "JURISDICTION", "Stabilization-jurisdiction.", "npc/metropolice/vo/stabilizationjurisdiction.wav")
Schema.voices.Add("Combine", "JURY", "Jury!", "npc/metropolice/vo/jury.wav")
Schema.voices.Add("Combine", "KEEP MOVING", "Keep moving!", "npc/metropolice/vo/keepmoving.wav")
Schema.voices.Add("Combine", "KILO", "Kilo.", "npc/combine_soldier/vo/kilo.wav")
Schema.voices.Add("Combine", "KING", "King!", "npc/metropolice/vo/king.wav")
Schema.voices.Add("Combine", "LAST SEEN AT", "Hiding, last seen at range...", "npc/metropolice/vo/hidinglastseenatrange.wav")
Schema.voices.Add("Combine", "LEADER", "Leader.", "npc/combine_soldier/vo/leader.wav")
Schema.voices.Add("Combine", "LEVEL 3", "I have a level three civil-privacy violator here!", "npc/metropolice/vo/level3civilprivacyviolator.wav")
Schema.voices.Add("Combine", "LINE", "Line!", "npc/metropolice/vo/line.wav")
Schema.voices.Add("Combine", "LOCATION", "Location?", "npc/metropolice/vo/location.wav")
Schema.voices.Add("Combine", "LOCK POSITION", "All units, lock your position!", "npc/metropolice/vo/lockyourposition.wav")
Schema.voices.Add("Combine", "LOCK", "Lock!", "npc/metropolice/vo/lock.wav")
Schema.voices.Add("Combine", "LOOK OUT", "Look out!", "npc/metropolice/vo/lookout.wav")
Schema.voices.Add("Combine", "LOOSE PARASITICS", "Loose parasitics!", "npc/metropolice/vo/looseparasitics.wav")
Schema.voices.Add("Combine", "LOST CONTACT", "Lost contact!", "npc/combine_soldier/vo/lostcontact.wav")
Schema.voices.Add("Combine", "LOW ON", "Running low on verdicts, taking cover!", "npc/metropolice/vo/runninglowonverdicts.wav")
Schema.voices.Add("Combine", "MACE", "Mace.", "npc/combine_soldier/vo/mace.wav")
Schema.voices.Add("Combine", "MAINTAIN CP", "All units, maintain this CP!", "npc/metropolice/vo/allunitsmaintainthiscp.wav")
Schema.voices.Add("Combine", "MALCOMPLIANCE", "Issuing malcompliance citation.", "npc/metropolice/vo/issuingmalcompliantcitation.wav")
Schema.voices.Add("Combine", "MALCOMPLIANT 10-107", "Malcompliant 10-107 at my 10-20, preparing to prosecute.", "npc/metropolice/vo/malcompliant10107my1020.wav")
Schema.voices.Add("Combine", "MALIGNANT", "Malignant!", "npc/metropolice/vo/malignant.wav")
Schema.voices.Add("Combine", "MATCH ON APB", "I have a match on APB likeness.", "npc/metropolice/vo/matchonapblikeness.wav")
Schema.voices.Add("Combine", "MINOR HITS", "Minor hits, continuing prosecution!", "npc/metropolice/vo/minorhitscontinuing.wav")
Schema.voices.Add("Combine", "MOVE ALONG", "Move along!", "npc/metropolice/vo/movealong.wav")
Schema.voices.Add("Combine", "MOVE BACK", "Move back, right now!", "npc/metropolice/vo/movebackrightnow.wav")
Schema.voices.Add("Combine", "MOVE IN", "Move in!", "npc/combine_soldier/vo/movein.wav")
Schema.voices.Add("Combine", "MOVE IT", "Move it!", "npc/metropolice/vo/moveit.wav")
Schema.voices.Add("Combine", "MOVE", "Move!", "npc/metropolice/vo/move.wav")
Schema.voices.Add("Combine", "MOVING TO COVER", "Moving to cover!", "npc/metropolice/vo/movingtocover.wav")
Schema.voices.Add("Combine", "MOVING TO HARDPOINT", "Moving to hardpoint!", "npc/metropolice/vo/movingtohardpoint.wav")
Schema.voices.Add("Combine", "NECROTICS", "Necrotics!", "npc/metropolice/vo/necrotics.wav")
Schema.voices.Add("Combine", "NEED ANY HELP", "Need any help with this one?", "npc/metropolice/vo/needanyhelpwiththisone.wav")
Schema.voices.Add("Combine", "NEEDS ASSISTANCE", "Officer needs assistance, I am 11-99!", "npc/metropolice/vo/officerneedsassistance.wav")
Schema.voices.Add("Combine", "NEEDS HELP", "Officer needs help!", "npc/metropolice/vo/officerneedshelp.wav")
Schema.voices.Add("Combine", "NO 647", "Clear, no 647, no 10-107.", "npc/metropolice/vo/clearno647no10-107.wav")
Schema.voices.Add("Combine", "NO CONTACT", "No contact!", "npc/metropolice/vo/nocontact.wav")
Schema.voices.Add("Combine", "NO I'M GOOD", "No, I'm good.", "vo/trainyard/ba_noimgood.wav")
Schema.voices.Add("Combine", "NO VISUAL ON", "No visual on UPI at this time.", "npc/metropolice/vo/novisualonupi.wav")
Schema.voices.Add("Combine", "NOMAD", "Nomad.", "npc/combine_soldier/vo/nomad.wav")
Schema.voices.Add("Combine", "NONCITIZEN", "Noncitizen.", "npc/metropolice/vo/noncitizen.wav")
Schema.voices.Add("Combine", "NONPATROL", "Non-patrol region.", "npc/metropolice/vo/nonpatrolregion.wav")
Schema.voices.Add("Combine", "NONTAGGED VIROMES", "Non-tagged viromes here!", "npc/metropolice/vo/non-taggedviromeshere.wav")
Schema.voices.Add("Combine", "NOVA", "Nova.", "npc/combine_soldier/vo/nova.wav")
Schema.voices.Add("Combine", "NOW GET OUT", "Now, get out of here!", "npc/metropolice/vo/nowgetoutofhere.wav")
Schema.voices.Add("Combine", "NOW", "Now.", "vo/trainyard/ba_thatbeer01.wav")
Schema.voices.Add("Combine", "OUTBREAK", "Outbreak!", "npc/combine_soldier/vo/outbreak.wav")
Schema.voices.Add("Combine", "OUTBREAK", "Outbreak!", "npc/metropolice/vo/outbreak.wav")
Schema.voices.Add("Combine", "OVERWATCH", "Overwatch.", "npc/combine_soldier/vo/overwatch.wav")
Schema.voices.Add("Combine", "PACIFYING", "Pacifying!", "npc/metropolice/vo/pacifying.wav")
Schema.voices.Add("Combine", "PAIN1", "Ugh!", "npc/metropolice/pain1.wav")
Schema.voices.Add("Combine", "PAIN2", "Uagh!", "npc/metropolice/pain2.wav")
Schema.voices.Add("Combine", "PAIN3", "Augh!", "npc/metropolice/pain3.wav")
Schema.voices.Add("Combine", "PAIN4", "Agh!", "npc/metropolice/pain4.wav")
Schema.voices.Add("Combine", "PATROL", "Patrol!", "npc/metropolice/vo/patrol.wav")
Schema.voices.Add("Combine", "PAYBACK", "Payback.", "npc/combine_soldier/vo/payback.wav")
Schema.voices.Add("Combine", "PHANTOM", "Phantom.", "npc/combine_soldier/vo/phantom.wav")
Schema.voices.Add("Combine", "PICKUP 647E", "Anyone else pick up a, uh... 647-E reading?", "npc/metropolice/vo/anyonepickup647e.wav")
Schema.voices.Add("Combine", "POSITION AT HARDPOINT", "In position at hardpoint.", "npc/metropolice/vo/inpositionathardpoint.wav")
Schema.voices.Add("Combine", "POSITION TO CONTAIN", "Position to contain.", "npc/metropolice/vo/positiontocontain.wav")
Schema.voices.Add("Combine", "POSSIBLE 404", "Possible 404 here!", "npc/metropolice/vo/possible404here.wav")
Schema.voices.Add("Combine", "POSSIBLE 647E", "Possible 647-E here, request AirWatch tag.", "npc/metropolice/vo/possible647erequestairwatch.wav")
Schema.voices.Add("Combine", "POSSIBLE ACCOMPLICE", "Report sightings of possible accomplice.", "npc/metropolice/vo/reportsightingsaccomplices.wav")
Schema.voices.Add("Combine", "POSSIBLE LEVEL 3", "Possible level three civil-privacy violator here!", "npc/metropolice/vo/possiblelevel3civilprivacyviolator.wav")
Schema.voices.Add("Combine", "PREPARING TO JUDGE", "Preparing to judge a 10-107, be advised.", "npc/metropolice/vo/preparingtojudge10-107.wav")
Schema.voices.Add("Combine", "PRESERVE", "Preserve!", "npc/metropolice/vo/preserve.wav")
Schema.voices.Add("Combine", "PRESSURE", "Pressure!", "npc/metropolice/vo/pressure.wav")
Schema.voices.Add("Combine", "PRIORITY 1", "Confirm, priority-one sighted.", "npc/metropolice/vo/confirmpriority1sighted.wav")
Schema.voices.Add("Combine", "PRIORITY 2", "I have a priority-two anti-citizen here!", "npc/metropolice/vo/priority2anticitizenhere.wav")
Schema.voices.Add("Combine", "PRODUCTION BLOCK", "Production-block.", "npc/metropolice/vo/productionblock.wav")
Schema.voices.Add("Combine", "PROSECUTE MALCOMPLIANT", "Ready to prosecute malcompliant citizen, final warning issued!", "npc/metropolice/vo/readytoprosecutefinalwarning.wav")
Schema.voices.Add("Combine", "PROSECUTE", "Prosecute!", "npc/metropolice/vo/prosecute.wav")
Schema.voices.Add("Combine", "PROSECUTING", "Prosecuting.", "npc/combine_soldier/vo/prosecuting.wav")
Schema.voices.Add("Combine", "PROTECTION COMPLETE", "Protection complete.", "npc/metropolice/vo/protectioncomplete.wav")
Schema.voices.Add("Combine", "QUICK", "Quick!", "npc/metropolice/vo/quick.wav")
Schema.voices.Add("Combine", "QUICKSAND", "Quicksand.", "npc/combine_soldier/vo/quicksand.wav")
Schema.voices.Add("Combine", "RANGE", "Range.", "npc/combine_soldier/vo/range.wav")
Schema.voices.Add("Combine", "RANGER", "Ranger.", "npc/combine_soldier/vo/ranger.wav")
Schema.voices.Add("Combine", "RAZOR", "Razor.", "npc/combine_soldier/vo/razor.wav")
Schema.voices.Add("Combine", "READY AMPUTATE", "Ready to amputate!", "npc/metropolice/vo/readytoamputate.wav")
Schema.voices.Add("Combine", "READY CHARGES", "Ready charges!", "npc/combine_soldier/vo/readycharges.wav")
Schema.voices.Add("Combine", "READY JUDGE", "Ready to judge.", "npc/metropolice/vo/readytojudge.wav")
Schema.voices.Add("Combine", "READY PROSECUTE", "Ready to prosecute!", "npc/metropolice/vo/readytoprosecute.wav")
Schema.voices.Add("Combine", "READY WEAPONS", "Ready weapons!", "npc/combine_soldier/vo/readyweapons.wav")
Schema.voices.Add("Combine", "REAPER", "Reaper.", "npc/combine_soldier/vo/reaper.wav")
Schema.voices.Add("Combine", "REINFORCEMENT TEAMS", "Reinforcement-teams, code three!", "npc/metropolice/vo/reinforcementteamscode3.wav")
Schema.voices.Add("Combine", "REPORT CLEAR", "Reporting clear.", "npc/combine_soldier/vo/reportingclear.wav")
Schema.voices.Add("Combine", "REPORT IN", "CP requests all units, uhh... Location report-in.", "npc/metropolice/vo/cprequestsallunitsreportin.wav")
Schema.voices.Add("Combine", "REPORT LOCATION", "All units, report location suspect!", "npc/metropolice/vo/allunitsreportlocationsuspect.wav")
Schema.voices.Add("Combine", "REPORT STATUS", "Local CP-teams, report status.", "npc/metropolice/vo/localcptreportstatus.wav")
Schema.voices.Add("Combine", "REPURPOSED", "Repurposed area.", "npc/metropolice/vo/repurposedarea.wav")
Schema.voices.Add("Combine", "RESIDENTIAL BLOCK", "Residential block.", "npc/metropolice/vo/residentialblock.wav")
Schema.voices.Add("Combine", "RESPOND CODE 3", "All units at location, responding code three!", "npc/metropolice/vo/allunitsrespondcode3.wav")
Schema.voices.Add("Combine", "RESPONDING", "Responding.", "npc/metropolice/vo/responding2.wav")
Schema.voices.Add("Combine", "RESTRICT", "Restrict!", "npc/metropolice/vo/restrict.wav")
Schema.voices.Add("Combine", "RESTRICTED", "Restricted block.", "npc/metropolice/vo/restrictedblock.wav")
Schema.voices.Add("Combine", "RESTRICTION ZONE", "Terminal restriction-zone!", "npc/metropolice/vo/terminalrestrictionzone.wav")
Schema.voices.Add("Combine", "RIPCORD", "Ripcord!", "npc/combine_soldier/vo/ripcord.wav")
Schema.voices.Add("Combine", "RODGER THAT", "Rodger that!", "npc/metropolice/vo/rodgerthat.wav")
Schema.voices.Add("Combine", "ROLLER", "Roller!", "npc/metropolice/vo/roller.wav")
Schema.voices.Add("Combine", "RUNNING", "He's running!", "npc/metropolice/vo/hesrunning.wav")
Schema.voices.Add("Combine", "SACRIFICE CODE", "All units, sacrifice code one and maintain this CP!", "npc/metropolice/vo/sacrificecode1maintaincp.wav")
Schema.voices.Add("Combine", "SAVAGE", "Savage.", "npc/combine_soldier/vo/savage.wav")
Schema.voices.Add("Combine", "SCAR", "Scar.", "npc/combine_soldier/vo/scar.wav")
Schema.voices.Add("Combine", "SEARCH", "Search!", "npc/metropolice/vo/search.wav")
Schema.voices.Add("Combine", "SEARCHING FOR SUSPECT", "Searching for suspect.", "npc/metropolice/vo/searchingforsuspect.wav")
Schema.voices.Add("Combine", "SECOND WARNING", "This is your second warning!", "npc/metropolice/vo/thisisyoursecondwarning.wav")
Schema.voices.Add("Combine", "SECTOR NOT STERILE", "Confirmed- sector not sterile.", "npc/combine_soldier/vo/confirmsectornotsterile.wav")
Schema.voices.Add("Combine", "SECTOR NOT SECURE", "Sector is not secure.", "npc/combine_soldier/vo/sectorisnotsecure.wav")
Schema.voices.Add("Combine", "SECURE ADVANCE", "Assault-point secured, advance!", "npc/metropolice/vo/assaultpointsecureadvance.wav")
Schema.voices.Add("Combine", "SECURE", "Secure.", "npc/combine_soldier/vo/secure.wav")
Schema.voices.Add("Combine", "SENTENCE", "Sentence delivered.", "npc/metropolice/vo/sentencedelivered.wav")
Schema.voices.Add("Combine", "SERVE", "Serve.", "npc/metropolice/vo/serve.wav")
Schema.voices.Add("Combine", "SHADOW", "Shadow.", "npc/combine_soldier/vo/shadow.wav")
Schema.voices.Add("Combine", "SHARPZONE", "Sharpzone.", "npc/combine_soldier/vo/sharpzone.wav")
Schema.voices.Add("Combine", "SHIT", "Shit!", "npc/metropolice/vo/shit.wav")
Schema.voices.Add("Combine", "SHOTS FIRED", "Shots fired, hostile malignants here!", "npc/metropolice/vo/shotsfiredhostilemalignants.wav")
Schema.voices.Add("Combine", "SLAM", "Slam.", "npc/combine_soldier/vo/slam.wav")
Schema.voices.Add("Combine", "SLASH", "Slash.", "npc/combine_soldier/vo/slash.wav")
Schema.voices.Add("Combine", "SOCIOCIDE", "Sociocide.", "npc/metropolice/vo/sociocide.wav")
Schema.voices.Add("Combine", "SOCIOSTABLE", "We are socio-stable at this location.", "npc/metropolice/vo/wearesociostablethislocation.wav")
Schema.voices.Add("Combine", "SPEAR", "Spear.", "npc/combine_soldier/vo/spear.wav")
Schema.voices.Add("Combine", "STAB", "Stab.", "npc/combine_soldier/vo/stab.wav")
Schema.voices.Add("Combine", "STANDING BY", "Standing by.", "npc/combine_soldier/vo/standingby].wav")
Schema.voices.Add("Combine", "STAR", "Star.", "npc/combine_soldier/vo/star.wav")
Schema.voices.Add("Combine", "STATIONBLOCK", "Stationblock.", "npc/metropolice/vo/stationblock.wav")
Schema.voices.Add("Combine", "STAY ALERT", "Stay alert.", "npc/combine_soldier/vo/stayalert.wav")
Schema.voices.Add("Combine", "STERILIZE", "Sterilize!", "npc/metropolice/vo/sterilize.wav")
Schema.voices.Add("Combine", "STINGER", "Stinger.", "npc/combine_soldier/vo/stinger.wav")
Schema.voices.Add("Combine", "STORM", "Storm.", "npc/combine_soldier/vo/storm.wav")
Schema.voices.Add("Combine", "STRIKE", "Striker.", "npc/combine_soldier/vo/striker.wav")
Schema.voices.Add("Combine", "SUBJECT 505", "Subject is 505!", "npc/metropolice/vo/subjectis505.wav")
Schema.voices.Add("Combine", "SUBJECT HIGH SPEED", "All units, be advised, subject is now high-speed!", "npc/metropolice/vo/subjectisnowhighspeed.wav")
Schema.voices.Add("Combine", "SUBJECT", "Subject!", "npc/metropolice/vo/subject.wav")
Schema.voices.Add("Combine", "SUNDOWN", "Sundown.", "npc/combine_soldier/vo/sundown.wav")
Schema.voices.Add("Combine", "SUSPECT INCURSION", "Disp reports suspect-incursion at location.", "npc/metropolice/vo/dispreportssuspectincursion.wav")
Schema.voices.Add("Combine", "SUSPECT MOVED TO", "Suspect has moved now to...", "npc/metropolice/vo/supsecthasmovednowto.wav")
Schema.voices.Add("Combine", "SUSPECT RESTRICTED CANALS", "Suspect is using restricted canals at...", "npc/metropolice/vo/suspectusingrestrictedcanals.wav")
Schema.voices.Add("Combine", "SUSPEND", "Suspend!", "npc/metropolice/vo/suspend.wav")
Schema.voices.Add("Combine", "SWEEPER", "Sweeper.", "npc/combine_soldier/vo/sweeper.wav")
Schema.voices.Add("Combine", "SWEEPING IN", "Sweeping in!", "npc/combine_soldier/vo/sweepingin.wav")
Schema.voices.Add("Combine", "SWEEPING SUSPECT", "Sweeping for suspect!", "npc/metropolice/vo/sweepingforsuspect.wav")
Schema.voices.Add("Combine", "SWIFT", "Swift.", "npc/combine_soldier/vo/swift.wav")
Schema.voices.Add("Combine", "SWORD", "Sword.", "npc/combine_soldier/vo/sword.wav")
Schema.voices.Add("Combine", "TAG 10-91D", "Tag 10-91d!", "npc/metropolice/vo/tag10-91d.wav")
Schema.voices.Add("Combine", "TAG BUG", "Tag one bug!", "npc/metropolice/vo/tagonebug.wav")
Schema.voices.Add("Combine", "TAG NECROTIC", "Tag one necrotic!", "npc/metropolice/vo/tagonenecrotic.wav")
Schema.voices.Add("Combine", "TAG PARASITIC", "Tag one parasitic!", "npc/metropolice/vo/tagoneparasitic.wav")
Schema.voices.Add("Combine", "TAKE A LOOK", "Going to take a look!", "npc/metropolice/vo/goingtotakealook.wav")
Schema.voices.Add("Combine", "TAKE COVER", "Take cover!", "npc/metropolice/vo/takecover.wav")
Schema.voices.Add("Combine", "TAP", "Tap!", "npc/metropolice/vo/tap.wav")
Schema.voices.Add("Combine", "TARGET", "Target.", "npc/combine_soldier/vo/target.wav")
Schema.voices.Add("Combine", "TEAM ADVANCE", "Team in position, advance!", "npc/metropolice/vo/teaminpositionadvance.wav")
Schema.voices.Add("Combine", "TEAM HOLDING", "Stabilization team holding in position.", "npc/combine_soldier/vo/stabilizationteamholding.wav")
Schema.voices.Add("Combine", "THERE HE GOES", "There he goes! He's at...", "npc/metropolice/vo/therehegoeshesat.wav")
Schema.voices.Add("Combine", "THERE HE IS", "There he is!", "npc/metropolice/vo/thereheis.wav")
Schema.voices.Add("Combine", "TRACKER", "Tracker.", "npc/combine_soldier/vo/tracker.wav")
Schema.voices.Add("Combine", "TRANSITBLOCK", "Transit-block.", "npc/metropolice/vo/transitblock.wav")
Schema.voices.Add("Combine", "TROUBLE", "Lookin' for trouble?", "npc/metropolice/vo/lookingfortrouble.wav")
Schema.voices.Add("Combine", "UNDER FIRE", "Officer under fire, taking cover!", "npc/metropolice/vo/officerunderfiretakingcover.wav")
Schema.voices.Add("Combine", "UNIFORM", "Uniform.", "npc/combine_soldier/vo/uniform.wav")
Schema.voices.Add("Combine", "UNION", "Union!", "npc/metropolice/vo/union.wav")
Schema.voices.Add("Combine", "UNKNOWN", "Suspect location unknown.", "npc/metropolice/vo/suspectlocationunknown.wav")
Schema.voices.Add("Combine", "UP THERE", "He's up there!", "npc/metropolice/vo/hesupthere.wav")
Schema.voices.Add("Combine", "UPI", "UPI.", "npc/metropolice/vo/upi.wav")
Schema.voices.Add("Combine", "UTL SUSPECT", "UTL that suspect.", "npc/metropolice/vo/utlthatsuspect.wav")
Schema.voices.Add("Combine", "UTL", "UTL suspect.", "npc/metropolice/vo/utlsuspect.wav")
Schema.voices.Add("Combine", "VACATE", "Vacate, citizen!", "npc/metropolice/vo/vacatecitizen.wav")
Schema.voices.Add("Combine", "VAMP", "Vamp.", "npc/combine_soldier/vo/vamp.wav")
Schema.voices.Add("Combine", "VERDICT", "You want a malcompliance verdict?", "npc/metropolice/vo/youwantamalcomplianceverdict.wav")
Schema.voices.Add("Combine", "VICE", "Vice!", "npc/metropolice/vo/vice.wav")
Schema.voices.Add("Combine", "VICTOR", "Victor!", "npc/metropolice/vo/victor.wav")
Schema.voices.Add("Combine", "VISCON", "Viscon.", "npc/combine_soldier/vo/viscon.wav")
Schema.voices.Add("Combine", "VISUAL EXOGEN", "Visual on exogen.", "npc/combine_soldier/vo/visualonexogens.wav")
Schema.voices.Add("Combine", "WARNING GIVEN", "Second warning given!", "npc/metropolice/vo/secondwarning.wav")
Schema.voices.Add("Combine", "WASTERIVER", "Wasteriver.", "npc/metropolice/vo/wasteriver.wav")
Schema.voices.Add("Combine", "WATCH IT", "Watch it!", "npc/metropolice/vo/watchit.wav")
Schema.voices.Add("Combine", "WINDER", "Winder.", "npc/combine_soldier/vo/winder.wav")
Schema.voices.Add("Combine", "WORKFORCE", "Workforce intake.", "npc/metropolice/vo/workforceintake.wav")
Schema.voices.Add("Combine", "WRAP IT UP", "That's it, wrap it up.", "npc/combine_soldier/vo/thatsitwrapitup.wav")
Schema.voices.Add("Combine", "XRAY", "XRay!", "npc/metropolice/vo/xray.wav")
Schema.voices.Add("Combine", "YELLOW", "Yellow!", "npc/metropolice/vo/yellow.wav")
Schema.voices.Add("Combine", "YOU CAN GO", "Alright, you can go.", "npc/metropolice/vo/allrightyoucango.wav")
Schema.voices.Add("Combine", "ZONE", "Zone!", "npc/metropolice/vo/zone.wav")

Schema.voices.Add("Dispatch", "ACTIVITY LEVEL 1", "You are charged with anti-civil activity level: ONE. Protection-unit prosecution code: DUTY, SWORD, OPERATE.", "npc/overwatch/cityvoice/f_anticivil1_5_spkr.wav", true)
Schema.voices.Add("Dispatch", "ANTI-CITIZEN", "Attention, ground-units: Anti-citizen reported in this community. Code: LOCK, CAUTERIZE, STABILIZE.", "npc/overwatch/cityvoice/f_anticitizenreport_spkr.wav", true)
Schema.voices.Add("Dispatch", "ANTI-CIVIL EVIDENCE", "Protection-team, alert: Evidence of anti-civil activity in this community. Code: ASSEMBLE, CLAMP, CONTAIN.", "npc/overwatch/cityvoice/f_anticivilevidence_3_spkr.wav", true)
Schema.voices.Add("Dispatch", "ARE CHARGED WITH", "Individual, you are charged with capital malcompliance. Anti-citizen status, APPROVED.", "npc/overwatch/cityvoice/f_capitalmalcompliance_spkr.wav", true)
Schema.voices.Add("Dispatch", "ASSUME POSITIONS", "Attention, please: All citizens in local residential block, assume your inspection-positions.", "npc/overwatch/cityvoice/f_trainstation_assumepositions_spkr.wav", true)
Schema.voices.Add("Dispatch", "AUTONOMOUS JUDGMENT", "Attention, all ground-protection teams, autonomous judgment is now in effect. Sentencing is now discretionary. Code, AMPUTATE, ZERO, CONFIRM.", "npc/overwatch/cityvoice/f_protectionresponse_4_spkr.wav", true)
Schema.voices.Add("Dispatch", "CITIZEN RELOCATION", "Citizen notice: Failure to co-operate will result in permanent off-world relocation.", "npc/overwatch/cityvoice/f_trainstation_offworldrelocation_spkr.wav", true)
Schema.voices.Add("Dispatch", "CONSPIRACY", "Citizen reminder: Inaction is conspiracy. Report counter-behavior to a Civil-Protection team immediately.", "npc/overwatch/cityvoice/f_innactionisconspiracy_spkr.wav", true)
Schema.voices.Add("Dispatch", "CONVICTED", "Individual, you are convicted of multi-anti-civil violations. Implict citizenship revoked. Status, MALIGNANT.", "npc/overwatch/cityvoice/f_citizenshiprevoked_6_spkr.wav", true)
Schema.voices.Add("Dispatch", "DEDUCTED", "Attention, occupants: Your block is now charged with permissive inactive coersion. Five ration-units deducted.", "npc/overwatch/cityvoice/f_rationunitsdeduct_3_spkr.wav", true)
Schema.voices.Add("Dispatch", "EVASION BEHAVIOR", "Attention, please, evasion behaviour consistent with malcompliant defendant. Ground protection-team, alert, code: ISOLATE, EXPOSE, ADMINISTER.", "npc/overwatch/cityvoice/f_evasionbehavior_2_spkr.wav", true)
Schema.voices.Add("Dispatch", "INDIVIDUAL CHARGED WITH", "Individual, you are charged with socio-endangerment level: ONE. Protection-unit prosecution code, DUTY, SWORD, MIDNIGHT.", "npc/overwatch/cityvoice/f_sociolevel1_4_spkr.wav", true)
Schema.voices.Add("Dispatch", "INSPECTION", "Citizen notice, priority identification-check in-progress. Please assemble in your designated inspection positions.", "npc/overwatch/cityvoice/f_trainstation_assemble_spkr.wav", true)
Schema.voices.Add("Dispatch", "JUDGMENT WAIVER", "Attention, all ground-protection teams, judgment waiver now in effect. Capital prosecution is discretionary.", "npc/overwatch/cityvoice/f_protectionresponse_5_spkr.wav", true)
Schema.voices.Add("Dispatch", "MISCOUNT DETECTED", "Attention, residents: Miscount detected in your block. Co-operation with your Civil Protection team permits full ration reward.", "npc/overwatch/cityvoice/f_trainstation_cooperation_spkr.wav", true)
Schema.voices.Add("Dispatch", "MISSION FAILURE", "Attention, ground-units: Mission-failure will result in permanent off-world assignment. Code-reminder: SACRIFICE, COAGULATE, CLAMP.", "npc/overwatch/cityvoice/fprison_missionfailurereminder.wav", true)
Schema.voices.Add("Dispatch", "OVERWATCH ACKNOWLEDGES", "Overwatch acknowledges critical exogen-breach. AirWatch augmentation-force dispatched and inbound. Hold for re-enforcement.", "npc/overwatch/cityvoice/fprison_airwatchdispatched.wav", true)
Schema.voices.Add("Dispatch", "POTENTIAL INFECTION", "Attention, residents: This blocks contains potential civil infection. INFORM, CO-OPERATE, ASSEMBLE.", "npc/overwatch/cityvoice/f_trainstation_inform_spkr.wav", true)
Schema.voices.Add("Dispatch", "RECEIVE YOUR VERDICT", "Individual, you are now charged with socio-endangerment level: FIVE. Cease evasion immediately, recieve your verdict.", "npc/overwatch/cityvoice/f_ceaseevasionlevelfive_spkr.wav", true)
Schema.voices.Add("Dispatch", "STATUS EVASION", "Attention, protection-team, status evasion in progress in this community. RESPOND, ISOLATE, INQUIRE.", "npc/overwatch/cityvoice/f_protectionresponse_1_spkr.wav", true)
Schema.voices.Add("Dispatch", "UNIDENTIFIED", "Attention, please: Unidentified person of interest, confirm your civil status with local protection-team immediately.", "npc/overwatch/cityvoice/f_confirmcivilstatus_1_spkr.wav", true)
Schema.voices.Add("Dispatch", "UNREST PROCEDURE", "Attention, community: Unrest procedure code is now in effect. INNOCULATE, SHIELD, PACIFY. Code: PRESSURE, SWORD, STERILIZE.", "npc/overwatch/cityvoice/f_unrestprocedure1_spkr.wav", true)
Schema.voices.Add("Dispatch", "UNREST STRUCTURE", "Alert, community ground-protection units, local unrest structure detected. ASSEMBLE, ADMINISTER, PACIFY.", "npc/overwatch/cityvoice/f_localunrest_spkr.wav", true)

Schema.voices.AddClass("Combine", function(client)
	return client:IsCombine()
end)

Schema.voices.AddClass("Dispatch", function(client)
	return client:IsDispatch()
end)

Schema.voices.Add("Vortigaunt", "ACCOMPANY", "Gladly we accompany", "vo/npc/vortigaunt/accompany.wav")
Schema.voices.Add("Vortigaunt", "ACIDLIONS", "Beware the acid-lions. Their corrosive spray permits quick carving of rock passages, but also serves as a strong deterrent to hive robbers like ourselves.", "vo/outland_03_04/tunnels/vort_extract_acidinfo05.wav")
Schema.voices.Add("Vortigaunt", "AFFIRMED", "Affirmed", "vo/npc/vortigaunt/affirmed.wav")
Schema.voices.Add("Vortigaunt", "AGREED", "Agreed", "vo/outland_03_04/tunnels/vort_extract_agreed.wav")
Schema.voices.Add("Vortigaunt", "AGREED2", "Agreed", "vo/npc/vortigaunt/vort_grp_agree02.wav")
Schema.voices.Add("Vortigaunt", "AH", "Ah...", "vo/npc/vortigaunt/vort_grp_agree04.wav")
Schema.voices.Add("Vortigaunt", "AH YES", "Ah, yes.", "vo/outland_03_04/tunnels/vort_extract_ahyes.wav")
Schema.voices.Add("Vortigaunt", "AH2", "Ah...", "vo/npc/vortigaunt/vort_grp_greetings04.wav")
Schema.voices.Add("Vortigaunt", "AHGLAH", "Ahglah...", "vo/npc/vortigaunt/vortigese02.wav")
Schema.voices.Add("Vortigaunt", "ALERT", "Alert!", "vo/npc/vortigaunt/alert.wav")
Schema.voices.Add("Vortigaunt", "ALL DEAR", "We have lost all dear to us", "vo/npc/vortigaunt/alldear.wav")
Schema.voices.Add("Vortigaunt", "ALL FOR NOW", "That is all, for now", "vo/npc/vortigaunt/allfornow.wav")
Schema.voices.Add("Vortigaunt", "ALL IN ONE", "All in one, and one in all", "vo/npc/vortigaunt/allinoneinall.wav")
Schema.voices.Add("Vortigaunt", "ALL WE CAN SPARE", "That is all we can spare", "vo/npc/vortigaunt/allwecanspare.wav")
Schema.voices.Add("Vortigaunt", "ALL WE HAVE", "All we have is yours", "vo/npc/vortigaunt/allwehave.wav")
Schema.voices.Add("Vortigaunt", "ALLOW ME", "Allow me", "vo/npc/vortigaunt/allowme.wav")
Schema.voices.Add("Vortigaunt", "ALMOST VORTAL", "Almost vortal, this bond between you...", "vo/outland_02/junction/vort_junc_almostvortal.wav")
Schema.voices.Add("Vortigaunt", "AN HONOR", "It is an honor", "vo/npc/vortigaunt/itishonor.wav")
Schema.voices.Add("Vortigaunt", "ANTLION HUSBANDRY", "Antlion husbandry was once our ancestral practice", "vo/outland_03_04/tunnels/vort_extract_bond03.wav")
Schema.voices.Add("Vortigaunt", "ANTLIONS", "Antlions!", "vo/outland_03_04/tunnels/vort_antlions_arrive_01.wav")
Schema.voices.Add("Vortigaunt", "AS YOU WISH", "As you wish", "vo/npc/vortigaunt/asyouwish.wav")
Schema.voices.Add("Vortigaunt", "ASSENT", "Assent.", "vo/npc/vortigaunt/assent.wav")
Schema.voices.Add("Vortigaunt", "ASSUME NOTHING", "Assume /nothing/", "vo/npc/vortigaunt/vanswer09.wav")
Schema.voices.Add("Vortigaunt", "ATTEMPT", "It appears they attempted an escape, but made it no farther than the abyss.", "vo/outland_06/bridge/vort_bridge_attempt.wav")
Schema.voices.Add("Vortigaunt", "ATTEND", "Attend, now and learn to shepherd antlions with this so-called bug-bait.", "vo/coast/bugbait/vbaittrain01c.wav")
Schema.voices.Add("Vortigaunt", "ATTEND2", "Now, attend well. Apply pressure to your pheropod, to signal the antlions in your command to follow you.", "vo/coast/bugbait/vbaittrain04.wav")
Schema.voices.Add("Vortigaunt", "BE OF SERVICE", "Can we be of service", "vo/npc/vortigaunt/beofservice.wav")
Schema.voices.Add("Vortigaunt", "BEG YOUR AWARENESS", "We beg your awareness...", "vo/npc/vortigaunt/vanswer14.wav")
Schema.voices.Add("Vortigaunt", "BEHOLD", "Behold!", "vo/outland_02/junction/vort_junc_behold.wav")
Schema.voices.Add("Vortigaunt", "BOTH PARTIES", "Headcrabs have had their way with both parties.", "vo/outland_06/bridge/vort_bridge_nogoodend02.wav")
Schema.voices.Add("Vortigaunt", "BRIGHT FACE", "Your bright face obscures your darker mask", "vo/npc/vortigaunt/vmono_17.wav")
Schema.voices.Add("Vortigaunt", "BY OUR HONOR", "By our honor", "vo/npc/vortigaunt/ourhonor.wav")
Schema.voices.Add("Vortigaunt", "CALL1", "Shaaaa!", "vo/outland_01/intro/ol01_vortcall01.wav")
Schema.voices.Add("Vortigaunt", "CALL2", "Dey'nach? Sennah 'saa razh ah!", "vo/outland_01/intro/ol01_vortcall02c.wav")
Schema.voices.Add("Vortigaunt", "CALL3", "Dey'nahh?", "vo/outland_01/intro/ol01_vortresp01.wav")
Schema.voices.Add("Vortigaunt", "CALL4", "Shaa!", "vo/outland_01/intro/ol01_vortresp04.wav")
Schema.voices.Add("Vortigaunt", "CALM", "Calm Yourself", "vo/npc/vortigaunt/calm.wav")
Schema.voices.Add("Vortigaunt", "CAN WE NOT", "Can we not convince you otherwise", "vo/npc/vortigaunt/canconvince.wav")
Schema.voices.Add("Vortigaunt", "CANNOT HEAL", "We cannot heal a moving target", "vo/npc/vortigaunt/movingtarget.wav")
Schema.voices.Add("Vortigaunt", "CANNOT HOPE", "But I cannot hope to bring it back alone.", "vo/outland_03_04/tunnels/vort_extract_journeydeep02.wav")
Schema.voices.Add("Vortigaunt", "CAUTION", "Caution", "vo/npc/vortigaunt/caution.wav")
Schema.voices.Add("Vortigaunt", "CERTAINLY", "Certainly", "vo/npc/vortigaunt/certainly.wav")
Schema.voices.Add("Vortigaunt", "CHAA", "Chaa... Kurr? Par'aih...", "vo/outland_01/intro/vort_rbed_vemotings01.wav")
Schema.voices.Add("Vortigaunt", "CHAFING BONDS", "We have endured these chafing bonds for eons, yet a single moment of further servitude seems intolerable!", "vo/npc/vortigaunt/vmono_21.wav")
Schema.voices.Add("Vortigaunt", "CHASM", "Behold! Across the chasm!", "vo/outland_03_04/tunnels/vort_extract_vibchasm01.wav")
Schema.voices.Add("Vortigaunt", "CHUAA", "Chuaa'lung gunn', chellah gurr.", "vo/npc/vortigaunt/vortigese12.wav")
Schema.voices.Add("Vortigaunt", "CHURR", "Churr! Galih churr alla gunn'!", "vo/npc/vortigaunt/vortigese11.wav")
Schema.voices.Add("Vortigaunt", "CLAIM YOU", "We claim you", "vo/npc/vortigaunt/weclaimyou.wav")
Schema.voices.Add("Vortigaunt", "COMMUNION OF THE VORTESSENCE", "Communion of the vortessence, and that other: a deeper mystery. No deeper than the void itself.", "vo/npc/vortigaunt/vmono_08.wav")
Schema.voices.Add("Vortigaunt", "COMPANION", "There is no finer companion.", "vo/outland_03_04/tunnels/vort_extract_yescompanion02.wav")
Schema.voices.Add("Vortigaunt", "COMPANY", "We deem this company inviolable", "vo/npc/vortigaunt/vques09.wav")
Schema.voices.Add("Vortigaunt", "CONDITION", "That condition will not last long if you plunge into the toxins below.", "vo/outland_06/bridge/vort_bridge_takeupaim01.wav")
Schema.voices.Add("Vortigaunt", "CONSEQUENCES OF THIS STRUGGLE", "Your song we sing and shall sing for eternity. No matter the consequences of this struggle.", "vo/npc/vortigaunt/vmono_11.wav")
Schema.voices.Add("Vortigaunt", "CONSTANT OBSTACLES", "What next in the parade of constant obstacles?", "vo/outland_03_04/tunnels/vort_extract_constantobst.wav")
Schema.voices.Add("Vortigaunt", "CORPOREAL", "We never dream to meet you in corporeal form", "vo/npc/vortigaunt/corporeal.wav")
Schema.voices.Add("Vortigaunt", "COURTESY", "Yes, we will vocalize in your auditory language as a matter of courtesy.", "vo/coast/vgossip_02.wav")
Schema.voices.Add("Vortigaunt", "CRATES", "I think you will be very glad you saved those crates.", "vo/outland_03_04/tunnels/vort_extract_savedcrates02.wav")
Schema.voices.Add("Vortigaunt", "DEDICATE OURSELVES", "We dedicate ourselves to your purpose", "vo/npc/vortigaunt/dedicate.wav")
Schema.voices.Add("Vortigaunt", "DEFEND US", "Defend us!", "vo/outland_02/junction/vort_turret_defendus.wav")
Schema.voices.Add("Vortigaunt", "DELUDED", "You are deluded.", "vo/npc/vortigaunt/vanswer11.wav")
Schema.voices.Add("Vortigaunt", "DESCEND", "But how... How shall we descend?", "vo/outland_03_04/tunnels/vort_extract_howdescend.wav")
Schema.voices.Add("Vortigaunt", "DEVICE", "That immense repellant device promises surcease from endless antlion attacks.", "vo/outland_03_04/tunnels/vort_extract_vibchasm02.wav")
Schema.voices.Add("Vortigaunt", "DEVICE2", "Take shelter near the repellant device!", "vo/outland_05/canyon/vort_guard_alyxshelter01.wav")
Schema.voices.Add("Vortigaunt", "DEVICE3", "A vibratory oasis!", "vo/outland_05/canyon/vort_guard_alyxshelter03.wav")
Schema.voices.Add("Vortigaunt", "DISABLED", "I have disabled them.", "vo/outland_03_04/tunnels/vort_prone_nag_02.wav")
Schema.voices.Add("Vortigaunt", "DISTURBED", "For now we must not be disturbed.", "vo/outland_02/junction/vort_junc_assistance03.wav")
Schema.voices.Add("Vortigaunt", "DONE", "Done", "vo/npc/vortigaunt/done.wav")
Schema.voices.Add("Vortigaunt", "DONT RELY", "Don't rely on it", "vo/npc/vortigaunt/vanswer08.wav")
Schema.voices.Add("Vortigaunt", "DREAMS", "I only hope our dreams do not follow them.", "vo/outland_03_04/tunnels/vort_extract_dreamsdonotfollow02.wav")
Schema.voices.Add("Vortigaunt", "EMPOWER US", "Empower us", "vo/npc/vortigaunt/empowerus.wav")
Schema.voices.Add("Vortigaunt", "ENERGY EMPOWERS", "Its energy empowers us", "vo/npc/vortigaunt/energyempower.wav")
Schema.voices.Add("Vortigaunt", "EXCELLENT", "Excellent", "vo/npc/vortigaunt/vort_excellent.wav")
Schema.voices.Add("Vortigaunt", "EXCELLENT SHOOTING", "Excellent shooting", "vo/npc/vortigaunt/vort_excellentshooting.wav")
Schema.voices.Add("Vortigaunt", "EXCELLENT SHOT", "Excellent shot", "vo/npc/vortigaunt/vort_excellentshot.wav")
Schema.voices.Add("Vortigaunt", "EXCEPTIONAL", "Exceptional", "vo/npc/vortigaunt/vort_exceptional.wav")
Schema.voices.Add("Vortigaunt", "EXCUSE OUR", "Excuse our gauche vicissitudes.", "vo/npc/vortigaunt/vanswer13.wav")
Schema.voices.Add("Vortigaunt", "EXHAUSTED", "We have exhausted their immediate number", "vo/outland_02/junction/vort_junc_exhausted.wav")
Schema.voices.Add("Vortigaunt", "EXTRACT AROMA", "We must try another direction... The extract aroma is weaker here.", "vo/outland_03_04/tunnels/vort_extract_wrongway05.wav")
Schema.voices.Add("Vortigaunt", "FALSE VEILS", "It dissolves the false veils that divide the vortessence.", "vo/outland_03_04/tunnels/vort_extract_bond05.wav")
Schema.voices.Add("Vortigaunt", "FAR DISTANT EYES", "Far distant eyes look out through yours.", "vo/npc/vortigaunt/vmono_19.wav")
Schema.voices.Add("Vortigaunt", "FAREWELL", "Farewell", "vo/outland_02/junction/vort_junc_bye01.wav")
Schema.voices.Add("Vortigaunt", "FAREWELL2", "Likewise and farewell. It has been an honour.", "vo/outland_06/bridge/vort_bridge_farewell.wav")
Schema.voices.Add("Vortigaunt", "FARFETCHED", "Such a theory is hardly far-fetched.", "vo/outland_05/canyon/vort_canyon_farfetch.wav")
Schema.voices.Add("Vortigaunt", "FEELING IS MUTUAL", "The feeling is mutual", "vo/npc/vortigaunt/vanswer16.wav")
Schema.voices.Add("Vortigaunt", "FIGHT WITH US", "It is good now that you fight with us", "vo/npc/vortigaunt/vort_goodfightwithus.wav")
Schema.voices.Add("Vortigaunt", "FINEST QUALITY", "Secretions of the finest quality.", "vo/outland_03_04/tunnels/vort_extract_finequality01.wav")
Schema.voices.Add("Vortigaunt", "FOR FREEDOM", "For freedom", "vo/npc/vortigaunt/forfreedom.wav")
Schema.voices.Add("Vortigaunt", "FORGIVENESS IS NOT OURS TO BESTOW", "We cannot forget those whose cords you cut. Forgiveness is not ours to bestow.", "vo/npc/vortigaunt/vmono_09.wav")
Schema.voices.Add("Vortigaunt", "FORWARD", "Forward", "vo/npc/vortigaunt/forward.wav")
Schema.voices.Add("Vortigaunt", "GALLUMLUNG", "Gallum'lung", "vo/npc/vortigaunt/vortigese09.wav")
Schema.voices.Add("Vortigaunt", "GIVE OVER", "Give over your essense", "vo/npc/vortigaunt/giveover.wav")
Schema.voices.Add("Vortigaunt", "GLADLY", "Gladly", "vo/npc/vortigaunt/gladly.wav")
Schema.voices.Add("Vortigaunt", "GLORIOUS END", "To our glorious end", "vo/npc/vortigaunt/gloriousend.wav")
Schema.voices.Add("Vortigaunt", "GO SAFELY", "Go safely", "vo/outland_02/junction/vort_junc_bye02.wav")
Schema.voices.Add("Vortigaunt", "GREAT ANTICIPATION", "I will observe with great anticipation!", "vo/outland_03_04/tunnels/vort_extract_puzzling02.wav")
Schema.voices.Add("Vortigaunt", "GREATER RESISTANCE", "Expect ever-greater resistance as we proceed", "vo/outland_03_04/tunnels/vort_extract_keen02.wav")
Schema.voices.Add("Vortigaunt", "GRIEF AND JUBILATION", "You have brought us grief and jubilation beyond measure...", "vo/npc/vortigaunt/vmono_12.wav")
Schema.voices.Add("Vortigaunt", "GUARDIAN", "The guardian...", "vo/outland_05/canyon/vort_guard_surfacesighting.wav")
Schema.voices.Add("Vortigaunt", "GUARDIAN2", "The guardian!", "vo/outland_05/canyon/vort_guard_killit_nag_09.wav")
Schema.voices.Add("Vortigaunt", "GUARDIAN3", "Remember! Do not kill the guardian or the extract will be ruined!", "vo/outland_03_04/tunnels/vort_extract_donotkill.wav")
Schema.voices.Add("Vortigaunt", "GUARDIAN4", "The guardian bars our way, but now we are free to destroy it.", "vo/outland_05/canyon/vort_guard_killit_nag_03.wav")
Schema.voices.Add("Vortigaunt", "GUARDIAN5", "If we are to survive, this guardian must now die.", "vo/outland_05/canyon/vort_guard_killit_nag_06.wav")
Schema.voices.Add("Vortigaunt", "GUARDIAN6", "Kill the guardian now!", "vo/outland_05/canyon/vort_guard_killit_nag_08.wav")
Schema.voices.Add("Vortigaunt", "GUARDIAN7", "Ah, the ancient guardian! Retrieving the extract may not be unchallenging.", "vo/outland_03_04/tunnels/vort_extract_ancientguard.wav")
Schema.voices.Add("Vortigaunt", "GUARDIAN8", "The guardian's presence guarantees the nearness of larval clusters. They are commonly posted near the young.", "vo/outland_03_04/tunnels/vort_extract_nearness.wav")
Schema.voices.Add("Vortigaunt", "GUARDIAN9", "The guardian is enraged over our theft of the extract.", "vo/outland_05/canyon/vort_canyon_guardianrage01.wav")
Schema.voices.Add("Vortigaunt", "GULANGA", "Gulanga", "vo/npc/vortigaunt/vortigese08.wav")
Schema.voices.Add("Vortigaunt", "GUNN", "Gunn", "vo/npc/vortigaunt/vortigese07.wav")
Schema.voices.Add("Vortigaunt", "HALT", "Halt", "vo/npc/vortigaunt/halt.wav")
Schema.voices.Add("Vortigaunt", "HARDEST WORK", "You have done the hardest work, admitting entrance to this chamber.", "vo/outland_03_04/tunnels/vort_extract_hardwork03.wav")
Schema.voices.Add("Vortigaunt", "HEADY AROMA", "Ah! Such quantities of the larvae... Such a heady aroma.", "vo/outland_03_04/tunnels/vort_extract_larvalaroma.wav")
Schema.voices.Add("Vortigaunt", "HELP YOU", "We will help you", "vo/npc/vortigaunt/wewillhelp.wav")
Schema.voices.Add("Vortigaunt", "HERE", "Here", "vo/npc/vortigaunt/here.wav")
Schema.voices.Add("Vortigaunt", "HINDER OUR PROGRESS", "If it tries to hinder our progress, we will have no choice but to kill it.", "vo/outland_05/canyon/vort_canyon_guardianrage02.wav")
Schema.voices.Add("Vortigaunt", "HM", "Hm...", "vo/npc/vortigaunt/vort_grp_agree03.wav")
Schema.voices.Add("Vortigaunt", "HOLD", "Hold", "vo/npc/vortigaunt/hold.wav")
Schema.voices.Add("Vortigaunt", "HOLD STILL", "Hold still", "vo/npc/vortigaunt/holdstill.wav")
Schema.voices.Add("Vortigaunt", "HONOUR IS OURS", "The honour is ours", "vo/npc/vortigaunt/honorours.wav")
Schema.voices.Add("Vortigaunt", "HOPE", "Hope is in sight", "vo/npc/vortigaunt/vques03.wav")
Schema.voices.Add("Vortigaunt", "HOPELESS", "Our cause seems hopeless", "vo/npc/vortigaunt/hopeless.wav")
Schema.voices.Add("Vortigaunt", "HOPES AND DREAMS", "How many are there in you? Whose hopes and dreams do you encompass?", "vo/npc/vortigaunt/vmono_28.wav")
Schema.voices.Add("Vortigaunt", "HUMAN NEEDED", "A Human is needed...", "vo/outland_03_04/tunnels/vort_extract_humanmark.wav")
Schema.voices.Add("Vortigaunt", "HUMANS", "You humans, always in the qualidity.", "vo/npc/vortigaunt/vques08.wav")
Schema.voices.Add("Vortigaunt", "I DESCEND", "I descend!", "vo/outland_03_04/tunnels/vort_04_elevator_descend_01.wav")
Schema.voices.Add("Vortigaunt", "IF YOU MOVE", "If you move, we cannot help you", "vo/npc/vortigaunt/ifyoumove.wav")
Schema.voices.Add("Vortigaunt", "IMMEASURABLE LOSS", "We have averted an immeasurable loss...", "vo/outland_02/junction/vort_junc_immeasurable.wav")
Schema.voices.Add("Vortigaunt", "INDEED", "Indeed", "vo/npc/vortigaunt/vort_grp_agree06.wav")
Schema.voices.Add("Vortigaunt", "JOIN ME", "Join me", "vo/outland_03_04/tunnels/vort_extract_joinmefm02.wav")
Schema.voices.Add("Vortigaunt", "JOIN NOW", "Join now as we imbibe the extract.", "vo/outland_03_04/tunnels/vort_extract_imbibe.wav")
Schema.voices.Add("Vortigaunt", "JUST AS WELL", "It is just as well", "vo/npc/vortigaunt/vanswer04.wav")
Schema.voices.Add("Vortigaunt", "JUST SO", "Just so", "vo/coast/vgossip_04.wav")
Schema.voices.Add("Vortigaunt", "JUST SO2", "Just so", "vo/npc/vortigaunt/vort_grp_agree01.wav")
Schema.voices.Add("Vortigaunt", "KALAGH", "Kalagh!", "vo/npc/vortigaunt/vort_attack21.wav")
Schema.voices.Add("Vortigaunt", "KEEN", "The antlions are keen to our presence", "vo/outland_03_04/tunnels/vort_extract_keen01.wav")
Schema.voices.Add("Vortigaunt", "KILL IT", "At this time, you may kill it without consequence", "vo/outland_05/canyon/vort_guard_killit.wav")
Schema.voices.Add("Vortigaunt", "KILLED ANTLIONS", "We have killed many antlions", "vo/outland_02/junction/vort_junc_killedmanyyet01.wav")
Schema.voices.Add("Vortigaunt", "KIN SOME DISTANCE", "My kin are still some distance away", "vo/outland_02/junction/vort_junc_assistance02.wav")
Schema.voices.Add("Vortigaunt", "KNOW YOU", "We know you", "vo/npc/vortigaunt/weknowyou.wav")
Schema.voices.Add("Vortigaunt", "LARVAL EXTRACT", "Ah, excellent.. A bounty of larval extract.", "vo/outland_03_04/tunnels/vort_extract_bounty01.wav")
Schema.voices.Add("Vortigaunt", "LARVAL PELLET", "I see you too appreciate the larval pellet's properties.", "vo/outland_03_04/tunnels/vort_squishgrub04.wav")
Schema.voices.Add("Vortigaunt", "LEAD ON", "Lead on", "vo/npc/vortigaunt/leadon.wav")
Schema.voices.Add("Vortigaunt", "LEAD US", "Lead us", "vo/npc/vortigaunt/leadus.wav")
Schema.voices.Add("Vortigaunt", "LIE STILL", "Lie still...", "vo/outland_02/junction/vort_junc_liestill.wav")
Schema.voices.Add("Vortigaunt", "LIKEWISE", "Likewise, we assure", "vo/npc/vortigaunt/vanswer15.wav")
Schema.voices.Add("Vortigaunt", "LOST ALL DEAR", "We have lost all dear to us...", "vo/npc/vortigaunt/vques01.wav")
Schema.voices.Add("Vortigaunt", "LUNG", "Lung", "vo/npc/vortigaunt/vortigese05.wav")
Schema.voices.Add("Vortigaunt", "MAKE HASTE", "Make haste", "vo/outland_03_04/tunnels/vort_extract_makehaste.wav")
Schema.voices.Add("Vortigaunt", "MATTER HOURS", "A matter of hours", "vo/outland_02/junction/vort_junc_matterhours.wav")
Schema.voices.Add("Vortigaunt", "MINDS IN YOUR MIND", "Could you but see the eyes inside your own, the minds in your mind, you would see how much we share.", "vo/npc/vortigaunt/vmono_29.wav")
Schema.voices.Add("Vortigaunt", "MIRACULOUS", "Miraculous secretion.", "vo/outland_03_04/tunnels/vort_extract_pharynx.wav")
Schema.voices.Add("Vortigaunt", "MOMENT LONGER", "A moment longer", "vo/outland_02/junction/vort_junc_momentlonger.wav")
Schema.voices.Add("Vortigaunt", "MOST PRIZED", "The creatures exude many valuable compounds... But the extract is the most prized by far...", "vo/outland_03_04/tunnels/vort_extract_bond04.wav")
Schema.voices.Add("Vortigaunt", "MOUNTED GUN", "This mounted gun may prove useful.", "vo/outland_06/bridge/vort_bridge_thismountgun.wav")
Schema.voices.Add("Vortigaunt", "NECTARIUM", "I will make the journey to seek the extract deep within the nest, in the sacred nectarium.", "vo/outland_03_04/tunnels/vort_extract_journeydeep01.wav")
Schema.voices.Add("Vortigaunt", "NEXT MATTER", "Now to the next matter of urgency", "vo/outland_02/junction/vort_junc_nextmatter.wav")
Schema.voices.Add("Vortigaunt", "NO DISTANCE BETWEEN US", "There is no distance between us. No false veil of time or space may intervene.", "vo/npc/vortigaunt/vmono_04.wav")
Schema.voices.Add("Vortigaunt", "NO FEAR", "No fear, we will put you on the right road", "vo/outland_02/junction/vort_junc_rightroad.wav")
Schema.voices.Add("Vortigaunt", "NO GOOD END", "But came to no good end themselves.", "vo/outland_06/bridge/vort_bridge_nogoodend01.wav")
Schema.voices.Add("Vortigaunt", "NO GRATITUDE", "Our bonds are of nature, and require no gratitude.", "vo/outland_06/bridge/vort_bridge_honored.wav")
Schema.voices.Add("Vortigaunt", "NO PULSE", "No pulse!", "vo/outland_02/junction/vort_junc_nopulse01.wav")
Schema.voices.Add("Vortigaunt", "NO TIME", "There is no time, more antlions approach", "vo/outland_02/junction/vort_junc_object.wav")
Schema.voices.Add("Vortigaunt", "NODE NEXUS", "Node and nexus, feed upon this life!", "vo/npc/vortigaunt/nodenexus.wav")
Schema.voices.Add("Vortigaunt", "NOT THE FIRST", "You're not the first to harbor such illusions", "vo/npc/vortigaunt/vanswer02.wav")
Schema.voices.Add("Vortigaunt", "NOW ATTACK", "Now attack!", "vo/outland_03_04/tunnels/vort_prone_nag_03.wav")
Schema.voices.Add("Vortigaunt", "OBSERVE", "Observe how they fight on below, heedless of our escape...", "vo/outland_03_04/tunnels/vort_extract_observefight.wav")
Schema.voices.Add("Vortigaunt", "OCCUPIED", "Our hands are occupied", "vo/outland_01/intro/vort_rbed_letsgo01b.wav")
Schema.voices.Add("Vortigaunt", "OF THE SORT", "Nothing of the sort", "vo/npc/vortigaunt/vanswer10.wav")
Schema.voices.Add("Vortigaunt", "ONE BETWEEN THE WORLDS", "For a brief time you joined us, you were one between the worlds.", "vo/npc/vortigaunt/vmono_07.wav")
Schema.voices.Add("Vortigaunt", "ONWARD", "Onward", "vo/npc/vortigaunt/onward.wav")
Schema.voices.Add("Vortigaunt", "OPAQUE", "Your mind is opaque...", "vo/npc/vortigaunt/opaque.wav")
Schema.voices.Add("Vortigaunt", "OPPOSITE", "We believe the opposite", "vo/npc/vortigaunt/vanswer03.wav")
Schema.voices.Add("Vortigaunt", "OUR DELAY", "Our delay, regrettable...", "vo/outland_02/junction/vort_junc_weweredelayed.wav")
Schema.voices.Add("Vortigaunt", "OUR PLACE IS HERE", "Our place is here", "vo/npc/vortigaunt/ourplacehere.wav")
Schema.voices.Add("Vortigaunt", "PASS ON", "Pass on", "vo/npc/vortigaunt/passon.wav")
Schema.voices.Add("Vortigaunt", "PAY IN KIND", "The Combine will pay in kind for their depravity.", "vo/npc/vortigaunt/vques02.wav")
Schema.voices.Add("Vortigaunt", "PERSEVERE", "This is more than anyone can bare... But, we will persevere", "vo/npc/vortigaunt/persevere.wav")
Schema.voices.Add("Vortigaunt", "PESSIMISM", "Such pessimism will doom us all", "vo/npc/vortigaunt/vques05.wav")
Schema.voices.Add("Vortigaunt", "PITY", "Pity the generator that requires a Vortigaunt to operate it.", "vo/outland_03_04/tunnels/vort_extract_pitythegen.wav")
Schema.voices.Add("Vortigaunt", "PLEASANT UNDERFOOT", "They are quite pleasant underfoot, are they not?", "vo/outland_03_04/tunnels/vort_squishgrub01.wav")
Schema.voices.Add("Vortigaunt", "PLEASED TO SEE", "I am pleased to see at least you are unharmed.", "vo/outland_01/intro/vort_rbed_freeman02.wav")
Schema.voices.Add("Vortigaunt", "PLEASING SOUND", "Ah, such a pleasing sound and sensation.", "vo/outland_03_04/tunnels/vort_squishgrub02.wav")
Schema.voices.Add("Vortigaunt", "PLENITUDE", "It is all one in the plenitude", "vo/npc/vortigaunt/vanswer18.wav")
Schema.voices.Add("Vortigaunt", "POET", "Our finest poet describes it thus... Gallum gaka lillimah.", "vo/npc/vortigaunt/poet.wav")
Schema.voices.Add("Vortigaunt", "POIGNANT", "A poignant scene... an eternity's repose. It brings peaceful thoughts, does it not?", "vo/outland_03_04/tunnels/vort_extract_chairman.wav")
Schema.voices.Add("Vortigaunt", "POWERLESS", "The gun would appear to be powerless.", "vo/outland_06/bridge/vort_bridge_depleted02.wav")
Schema.voices.Add("Vortigaunt", "PREVAIL", "We shall prevail", "vo/npc/vortigaunt/prevail.wav")
Schema.voices.Add("Vortigaunt", "PROPITIOUS", "Propitious alliance", "vo/npc/vortigaunt/propitious.wav")
Schema.voices.Add("Vortigaunt", "PURPOSE IS MUTUAL", "Our purpose is mutual", "vo/npc/vortigaunt/mutual.wav")
Schema.voices.Add("Vortigaunt", "QUIET THEM", "We shall quiet them", "vo/outland_02/junction/vort_junc_quietthem.wav")
Schema.voices.Add("Vortigaunt", "REASON FOR DELAY", "Is there reason for delay", "vo/npc/vortigaunt/reasondelay.wav")
Schema.voices.Add("Vortigaunt", "REGRETTABLE", "This is regrettable...", "vo/npc/vortigaunt/regrettable.wav")
Schema.voices.Add("Vortigaunt", "REGRETTABLY TRUE", "Regrettably true...", "vo/outland_11a/silo/vort_silo_regrettablytrue.wav")
Schema.voices.Add("Vortigaunt", "REMAIN", "We will remain, if you so instruct", "vo/npc/vortigaunt/willremain.wav")
Schema.voices.Add("Vortigaunt", "RETURN ALL IN ONE", "Return to the all-in-one", "vo/npc/vortigaunt/returntoall.wav")
Schema.voices.Add("Vortigaunt", "RETURN VOID", "Return to the void", "vo/npc/vortigaunt/returnvoid.wav")
Schema.voices.Add("Vortigaunt", "RIPE", "The scent of ripe perfection beckons.", "vo/outland_03_04/tunnels/vort_extract_hardwork01.wav")
Schema.voices.Add("Vortigaunt", "RISE", "Now... Try carefully to rise", "vo/outland_02/junction/vort_junc_rise.wav")
Schema.voices.Add("Vortigaunt", "SACRIFICE", "What seems to you a seems to you a sacrifice is merely, to us, an oscillation. We do not fear the interval of darkness.", "vo/npc/vortigaunt/vmono_26.wav")
Schema.voices.Add("Vortigaunt", "SAD FATE", "The sad fate of these others is our good fortune", "vo/outland_03_04/tunnels/vort_breakweb02.wav")
Schema.voices.Add("Vortigaunt", "SATISFACTION", "Satisfaction...", "vo/npc/vortigaunt/satisfaction.wav")
Schema.voices.Add("Vortigaunt", "SAVE YOURSELF", "Save yourself!", "vo/outland_03_04/tunnels/vort_extract_tothelift02.wav")
Schema.voices.Add("Vortigaunt", "SCENT OF EXTRACT", "A wind from below, bears the scent of extract... The stuff we seek lies at the bottom of this pit.", "vo/outland_03_04/tunnels/vort_extract_wind.wav")
Schema.voices.Add("Vortigaunt", "SENTRIES", "I do not see their sentries.", "vo/outland_05/canyon/vort_canyon_enclavesentries02.wav")
Schema.voices.Add("Vortigaunt", "SENTRIES2", "Puzzling. The sentries should have spotted us by now.", "vo/outland_05/canyon/vort_canyon_puzzling.wav")
Schema.voices.Add("Vortigaunt", "SERVE", "We live to serve", "vo/npc/vortigaunt/livetoserve.wav")
Schema.voices.Add("Vortigaunt", "SERVE BETTER", "Perhaps we will serve you better here", "vo/npc/vortigaunt/servebetterhere.wav")
Schema.voices.Add("Vortigaunt", "SHALL NOT BE FORGOTTEN", "If not, your sacrifice shall not be forgotten.", "vo/outland_01/intro/vort_separation_goodbye03.wav")
Schema.voices.Add("Vortigaunt", "SHARP SPUR OF HOPE", "That sharp spur of hope has not dulled to this day. For once the lesser master lay defeated, we knew the greater must also fall in time.", "vo/npc/vortigaunt/vmono_15.wav")
Schema.voices.Add("Vortigaunt", "SHELTERED LOCATION", "My kin will meet us at a sheltered location beneath the surface", "vo/outland_01/intro/vort_rbed_companions01.wav")
Schema.voices.Add("Vortigaunt", "SIB", "We call you sib, although your mind and meaning are a mystery to us.", "vo/npc/vortigaunt/vmono_18.wav")
Schema.voices.Add("Vortigaunt", "SKILLS ARE FORMIDABLE", "Your skills are formidable", "vo/npc/vortigaunt/vort_skillsformidable.wav")
Schema.voices.Add("Vortigaunt", "SLIPPED OUR YOKE", "How often have we slipped our yoke, only to find it choking us again.", "vo/npc/vortigaunt/vmono_22.wav")
Schema.voices.Add("Vortigaunt", "SOMETHING SECRET STEERS US BOTH", "Something secret steers us both. We shall not name it.", "vo/npc/vortigaunt/vmono_20.wav")
Schema.voices.Add("Vortigaunt", "SPECULATION", "Idle speculation", "vo/npc/vortigaunt/vanswer06.wav")
Schema.voices.Add("Vortigaunt", "STAND CLEAR", "Stand clear", "vo/npc/vortigaunt/standclear.wav")
Schema.voices.Add("Vortigaunt", "STILL HERE", "We are still here...", "vo/npc/vortigaunt/stillhere.wav")
Schema.voices.Add("Vortigaunt", "SUBMERSION", "This will necessitate deep submersion in the vortessence.", "vo/outland_03_04/tunnels/vort_extract_injuriesdeep02.wav")
Schema.voices.Add("Vortigaunt", "SUCCESS", "Success", "vo/outland_01/intro/vort_separation_success02.wav")
Schema.voices.Add("Vortigaunt", "SUCCULENT", "The grubs are nothing if not... Succulent.", "vo/outland_03_04/tunnels/vort_squishgrub03.wav")
Schema.voices.Add("Vortigaunt", "SUMMON MY KIN", "Let me summon my kin", "vo/outland_01/intro/vort_rbed_freeman05.wav")
Schema.voices.Add("Vortigaunt", "SURGE", "We surge", "vo/npc/vortigaunt/surge.wav")
Schema.voices.Add("Vortigaunt", "SURVIVED DARKER TIMES", "We have survived darker times", "vo/npc/vortigaunt/vques06.wav")
Schema.voices.Add("Vortigaunt", "SURVIVED WORSE", "We have survived worse across the ages", "vo/npc/vortigaunt/seenworse.wav")
Schema.voices.Add("Vortigaunt", "TAHH", "Tahh", "vo/npc/vortigaunt/vortigese03.wav")
Schema.voices.Add("Vortigaunt", "TAKE A MOMENT", "This should only take a moment", "vo/outland_03_04/tunnels/vort_extract_bounty02.wav")
Schema.voices.Add("Vortigaunt", "TAKE OUR STAND", "We take our stand beside you here, upon this miserable rock.", "vo/npc/vortigaunt/vmono_24.wav")
Schema.voices.Add("Vortigaunt", "TALISMAN OF VICTORY", "With you beside us, a talisman of victory, the day of freedom draws nigh.", "vo/npc/vortigaunt/vmono_16.wav")
Schema.voices.Add("Vortigaunt", "TAPESTRY", "We are a tapestry woven of vortessence. It is the same for you if only you would see it.", "vo/npc/vortigaunt/vmono_27.wav")
Schema.voices.Add("Vortigaunt", "TETHER CUT", "The tether is cut", "vo/npc/vortigaunt/tethercut.wav")
Schema.voices.Add("Vortigaunt", "THAT IS ALL", "That is all", "vo/npc/vortigaunt/thatisall.wav")
Schema.voices.Add("Vortigaunt", "THE EXTRACT", "The extract!", "vo/outland_03_04/tunnels/vort_extract_theextract02.wav")
Schema.voices.Add("Vortigaunt", "THE EXTRACT2", "The extract!", "vo/outland_03_04/tunnels/vort_extract_theextract03.wav")
Schema.voices.Add("Vortigaunt", "THE WAY AHEAD IS DARK", "The way ahead is dark for the moment..", "vo/npc/vortigaunt/vmono_25.wav")
Schema.voices.Add("Vortigaunt", "THIS BODY", "This body is yours to command", "vo/npc/vortigaunt/bodyyours.wav")
Schema.voices.Add("Vortigaunt", "THIS MUCH", "We expected this much", "vo/npc/vortigaunt/vanswer05.wav")
Schema.voices.Add("Vortigaunt", "TO THE VOID", "To the void with you", "vo/npc/vortigaunt/tothevoid.wav")
Schema.voices.Add("Vortigaunt", "TOTAL VICTORY", "Let this war end in either total victory or our extinction. No further compromise shall we allow.", "vo/npc/vortigaunt/vmono_23.wav")
Schema.voices.Add("Vortigaunt", "TOUCHING", "Your concern is touching", "vo/npc/vortigaunt/vanswer07.wav")
Schema.voices.Add("Vortigaunt", "TRACES", "Such traces of former habitation somehow sadden me.", "vo/outland_03_04/tunnels/vort_extract_traces.wav")
Schema.voices.Add("Vortigaunt", "TRAITS", "You bear some traits we thought innate to vortikind.", "vo/outland_03_04/tunnels/vort_extract_bond02.wav")
Schema.voices.Add("Vortigaunt", "TRAUMATIC INJURY", "The Combine Hunters cause traumatic injury.", "vo/outland_02/junction/vort_junc_badlyinjured02.wav")
Schema.voices.Add("Vortigaunt", "TRAVEL WELL", "Travel well", "vo/outland_02/junction/vort_junc_bye03.wav")
Schema.voices.Add("Vortigaunt", "TROUBLE US NO MORE", "That one shall trouble us no more", "vo/npc/vortigaunt/troubleus.wav")
Schema.voices.Add("Vortigaunt", "TURNING POINT", "This marks a turning-point", "vo/npc/vortigaunt/vques04.wav")
Schema.voices.Add("Vortigaunt", "TURRLUNG", "Turr, lung gurr chalachurr gunn, gong lurr...", "vo/npc/vortigaunt/vortigese13.wav")
Schema.voices.Add("Vortigaunt", "UNACCUSTOMED", "This is unaccustomed", "vo/npc/vortigaunt/vanswer17.wav")
Schema.voices.Add("Vortigaunt", "UNCONVINCED", "We remain unconvinced", "vo/npc/vortigaunt/vanswer01.wav")
Schema.voices.Add("Vortigaunt", "UNDER ATTACK", "We are under attack!", "vo/outland_02/junction/vort_turret_helpcall04.wav")
Schema.voices.Add("Vortigaunt", "UNDESERVING", "Undeserving of consciousness", "vo/npc/vortigaunt/undeserving.wav")
Schema.voices.Add("Vortigaunt", "UNFLATTERING", "Unless we wish to say unflattering things about you.", "vo/coast/vgossip_03.wav")
Schema.voices.Add("Vortigaunt", "UNITY", "Unity of purpose; the shattering of common shackles, a single road we tread.", "vo/npc/vortigaunt/vmono_10.wav")
Schema.voices.Add("Vortigaunt", "URGENT ERRAND", "I fear a more urgent errand demands our attention.", "vo/outland_06/bridge/vort_bridge_hunt01.wav")
Schema.voices.Add("Vortigaunt", "URGENT NEED", "They will understand our urgent need.", "vo/outland_05/canyon/vort_canyon_reside02.wav")
Schema.voices.Add("Vortigaunt", "VORTICOUGH", "Weeeeeeeeeeeeeeeeeah-uh *Coughing*", "npc/vort/vort_pain3.wav")
Schema.voices.Add("Vortigaunt", "WE ARE HONORED", "We are honoured", "vo/npc/vortigaunt/wehonored.wav")
Schema.voices.Add("Vortigaunt", "WE ARE YOURS", "We are yours", "vo/npc/vortigaunt/weareyours.wav")
Schema.voices.Add("Vortigaunt", "WE FEAR", "We fear we have failed you", "vo/npc/vortigaunt/fearfailed.wav")
Schema.voices.Add("Vortigaunt", "WE FOLLOW YOU", "To our honor, we follow you", "vo/npc/vortigaunt/honorfollow.wav")
Schema.voices.Add("Vortigaunt", "WE HAVE DREAMED", "We have dreamed of this moment", "vo/npc/vortigaunt/dreamed.wav")
Schema.voices.Add("Vortigaunt", "WE KNIT", "We knit shattered bone, and restore circulatory integrity", "vo/outland_02/junction/vort_junc_knit.wav")
Schema.voices.Add("Vortigaunt", "WE NEED HELP", "We need help!", "vo/outland_02/junction/vort_turret_helpcall01")
Schema.voices.Add("Vortigaunt", "WE REQUIRE EXTRACT", "We require... The larval extract.", "vo/outland_03_04/tunnels/vort_extract_werequire.wav")
Schema.voices.Add("Vortigaunt", "WE SHARE", "We shall share the Vortessence", "vo/npc/vortigaunt/weshare.wav")
Schema.voices.Add("Vortigaunt", "WE STAY", "Here we stay", "vo/npc/vortigaunt/herewestay.wav")
Schema.voices.Add("Vortigaunt", "WELL IN HAND", "I have the situation well in hand!", "vo/outland_03_04/tunnels/vort_extract_tothelift03.wav")
Schema.voices.Add("Vortigaunt", "WELL STATED", "Well stated", "vo/npc/vortigaunt/vort_grp_agree07.wav")
Schema.voices.Add("Vortigaunt", "WHAT HARM", "What harm has come?", "vo/outland_01/intro/vort_rbed_whatharm.wav")
Schema.voices.Add("Vortigaunt", "WHERE", "Where", "vo/npc/vortigaunt/ware.wav")
Schema.voices.Add("Vortigaunt", "WHERE TO NOW", "Where to, now?... And to what end", "vo/npc/vortigaunt/whereto.wav")
Schema.voices.Add("Vortigaunt", "WISH YOU WERE", "We wish you were right...", "vo/npc/vortigaunt/vanswer12.wav")
Schema.voices.Add("Vortigaunt", "WITH PLEASURE", "With pleasure", "vo/npc/vortigaunt/pleasure.wav")
Schema.voices.Add("Vortigaunt", "WORK TOGETHER", "It is good now that we work together", "vo/npc/vortigaunt/vort_goodtogether.wav")
Schema.voices.Add("Vortigaunt", "WORTHLESS", "Our life is worthless... Unless spent on freedom", "vo/npc/vortigaunt/worthless.wav")
Schema.voices.Add("Vortigaunt", "YES", "Yes", "vo/npc/vortigaunt/yes.wav")
Schema.voices.Add("Vortigaunt", "YES FORWARD", "Yes, forward", "vo/npc/vortigaunt/yesforward.wav")
Schema.voices.Add("Vortigaunt", "YES2", "Yes", "vo/npc/vortigaunt/vort_grp_agree05.wav")
Schema.voices.Add("Vortigaunt", "YET MANY REMAIN", "Yet many more remain", "vo/outland_02/junction/vort_junc_killedmanyyet02.wav")

Schema.voices.AddClass("Vortigaunt", function(client)
	return client:GetCharacter():IsVortigaunt()
end)
